CITATION.cff: create citation file
ASFHyP3/hyp3-docs pull request #218
Opened 2022-05-23 17:07 UTC by forrestfwilliams

2022-05-23 17:09 UTC, asjohnston-asf commented
.cff file reference: https://citation-file-format.github.io/

2022-05-23 17:14 UTC, forrestfwilliams commented
Right now this reference points to the main HyP3 directory's DOI, but I'm unsure if this is the behavior we want.

2022-05-23 17:52 UTC, jhkennedy requested changes
We should also add a `.zenodo` file so the zenodo metadata maches this -- that could be in this PR or another (I lean towards the former)

Likewise, we'll want to do the same for at least hyp3, the plugins, etc. But probably all of our repositories.

2022-05-23 17:52 UTC, jhkennedy commented on CITATION.cff
> +doi: 10.5281/zenodo.6568160
```suggestion
doi: 10.5281/zenodo.4646138
```
I think we want to point to the hyp3-docs DOI for this DOI. It's common to cite the documentation as the citation for the overall concept and the specific repos/releases as well.

2022-05-23 20:32 UTC, forrestfwilliams commented
> We should also add a `.zenodo` file so the zenodo metadata maches this -- that could be in this PR or another (I lean towards the former)
> 
> Likewise, we'll want to do the same for at least hyp3, the plugins, etc. But probably all of our repositories.

We've decided to move this addition to a future PR.

2022-05-24 17:44 UTC, asjohnston-asf commented
LGTM, here's how it renders:
`Hogenson, K., Kristenson, H., Kennedy, J., Johnston, A., Rine, J., Logan, T., Zhu, J., Williams, F., Herrmann, J., Smale, J., & Meyer, F. (2020). Hybrid Pluggable Processing Pipeline (HyP3): A cloud-native infrastructure for generic processing of SAR data [Computer software]. https://doi.org/10.5281/zenodo.4646138`

2022-05-24 17:45 UTC, asjohnston-asf approved these changes

2022-05-24 17:45 UTC, merged